require("firebase/firestore");
const firebase = require("./config");
const db = firebase.firestore();

const product_names = [
  "Cam Cành",
  "Kush Class A",
  "King Glue",
  "Cam Lẻ",
  "Cam Điếu",
  "Kush Vụn",
  "Cam Lọc",
  "Golden Glue",
  "Kush Class A+",
  "G4B",
  "Kush Điếu",
  "Sgg",
  "Moon I",
  "Tarantula",
  "Doom Day",
  "Master Super Glue A++",
  "Durban Poison A",
  "Pink Candy A+",
  "Master Kush",
  "Original Fash",
  "Og",
  "Vpp",
  "Rove",
  "Imini",
  "Elemon",
  "Nn",
  "Pink Candy",
  "Kush Class",
  "Og Mp",
  "Cc",
  "Rg",
  "Og Kush",
  "Rd",
  "Gg4",
  "Purple Candy",
  "Kush Vụn Og",
  "Raw",
  "Original Glue",
  "Gelato",
  "Cookie Kush",
  "Mr.T",
  "Cookie Cam",
  "Venom Bite",
  "Mr.T Ver 2.0",
  "Purple Punch",
  "Super Og",
  "Hell Og",
  "Bn",
  "Blue Mango",
  "Ocb",
  "Sundae",
  "King Kush",
  "Cookie",
  "Cam Lọc Cành",
  "Forbidden Fruit",
  "Blue Dream",
  "Sherbet",
  "Sativa",
  "Black Water",
  "Kush",
  "Vụn Og",
  "Moon II",
  "Vụn Kush",
  "Cherry Kush",
  "Candy Land",
  "Cam Cookie",
  "Cookie Kush Mini",
  "Diamond",
  "Điếu Kush",
  "24K Gold",
  "Acid",
  "Super Glue A+",
  "Vụn Doomday",
  "Diamond A+",
  "Purple Punch A+",
  "Gsc",
  "Dc",
  "Diamond A",
  "Moon",
  "Brass Pen"
];

const docRef = db.collection("options").doc("options");
docRef
  .set({ product_names }, { merge: true })
  .then(() => {
    console.log("done");
  })
  .catch(error => {
    console.log("ERROR", error);
  });
