require("firebase/firestore");
const firebase = require("./config");
const db = firebase.firestore();

const product_names = [
  "24K Gold",
  "Acid",
  "Black Water",
  "Blue Dream",
  "Blue Mango",
  "Bn",
  "Brass Pen",
  "Cam Cành",
  "Cam Cookie",
  "Cam Điếu",
  "Cam Lẻ",
  "Cam Lọc",
  "Cam Lọc Cành",
  "Candy Land",
  "Cc",
  "Cherry Kush",
  "Cookie",
  "Cookie Cam",
  "Cookie Kush",
  "Cookie Kush Mini",
  "Dc",
  "Diamond ",
  "Diamond A",
  "Diamond A+",
  "Điếu Kush",
  "Doom Day",
  "Durban Poison A",
  "Elemon",
  "Forbidden Fruit",
  "G4B",
  "Gelato",
  "Gg4",
  "Golden Glue",
  "Gsc",
  "Hell Og",
  "Imini",
  "King Glue",
  "King Kush",
  "Kush",
  "Kush Class ",
  "Kush Class A",
  "Kush Class A+",
  "Kush Điếu",
  "Kush Vụn",
  "Kush Vụn Og",
  "Master Kush",
  "Master Super Glue A++",
  "Moon",
  "Moon I",
  "Moon II",
  "Mr.T",
  "Mr.T Ver 2.0",
  "Nn",
  "Ocb",
  "Og",
  "Og Kush",
  "Og Mp",
  "Original Fash",
  "Original Glue",
  "Pink Candy",
  "Pink Candy A+",
  "Purple Candy",
  "Purple Punch",
  "Purple Punch A+",
  "Raw",
  "Rd",
  "Rg",
  "Rove",
  "Sativa",
  "Sgg",
  "Sherbet",
  "Sundae",
  "Super Glue A+",
  "Super Og",
  "Tarantula",
  "Venom Bite",
  "Vpp",
  "Vụn Doomday",
  "Vụn Kush",
  "Vụn Og"
];

const docRef = db.collection("options").doc("options");
docRef
  .set({ product_names }, { merge: true })
  .then(() => {
    console.log("done");
  })
  .catch(error => {
    console.log("ERROR", error);
  });
